services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:14.18
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10


    volumes:
      - agregio-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  agregio-postgres-data:
